# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "IFF-0303"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Coronary Imaging Analysis":
        filters: ["coronary", "coronary artery", "CCTA", "CTA",
                  "coronary angiography", "x-ray angiography",
                  "IVUS", "intravascular ultrasound", "OCT",
                  "segmentation", "detection", "quantification",
                  "reconstruction", "registration"]

    "LLM Disease Prediction":
        filters: ["large language model", "LLM", "GPT", "Llama",
                  "MedGPT", "BioGPT", "Health-LLM",
                  "disease prediction", "diagnosis", "prognosis",
                  "risk prediction", "EHR", "EMR",
                  "electronic health record", "clinical note"]

    "Multimodal Disease Prediction":
        filters: ["multimodal", "multi-modal", "cross-modal",
                  "vision-language", "fusion",
                  "disease prediction", "diagnosis", "risk prediction",
                  "interpretability", "explainable AI", "explanation",
                  "evidence-guided", "saliency"]

    "Medical Image Restoration":
        filters: ["medical image", "inpainting", "image inpainting",
                  "image completion", "restoration",
                  "artifact removal", "artifact correction",
                  "denoising", "super-resolution",
                  "diffusion", "diffusion model", "DDPM",
                  "Stable Diffusion", "GAN", "masked autoencoder"]

